sudo: false
dist: focal
cache:
  apt: true
git:
  depth: false
addons:
  apt:
    packages:
    - build-essential
    - mingw-w64
script:
- autoreconf --install
- ./configure
- make
- make clean
- ./configure --host=x86_64-w64-mingw32
- make

